eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: msvc-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/usuario_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database_platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sensors
          uri: lb://MSVC-SENSORS
          predicates:
            - Path=/api/sensor/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
jwt:
  secret: llaveSecreta

