/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simulador_sensores.view;

import com.mycompany.simulador_sensores.dao.SensorDAO;
import com.mycompany.simulador_sensores.dao.iml.SensorDAOImpl;
import com.mycompany.simulador_sensores.data.DataSen;
import com.mycompany.simulador_sensores.data.impl.HumidityData;
import com.mycompany.simulador_sensores.data.impl.TemperatureData;
import com.mycompany.simulador_sensores.protocol.Protocol;
import com.mycompany.simulador_sensores.protocol.impl.CoapProtocol;
import com.mycompany.simulador_sensores.protocol.impl.MqttProtocol;
import com.mycompany.simulador_sensores.sensor.Sensor;
import com.mycompany.simulador_sensores.sensor.impl.HumiditySensor;
import com.mycompany.simulador_sensores.sensor.impl.TemperatureSensor;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class PantallaSensores extends javax.swing.JFrame {

    private final SensorDAO sensorDAO = SensorDAOImpl.getInstance();
    private boolean btnSensoresSelecionado = false;
    private RegistroSensorView registroSensorView;
    private List<Sensor> sensores;

    public PantallaSensores() {
        initComponents();
        cargarTabla();
        cargarDatosTabla();
        validarTitulo();
        registroSensorView = new RegistroSensorView(this);
    }

    private void cargarTabla() {
        setBackground(new Color(0, 0, 0, 0));
        tblSensores.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblSensores.getTableHeader().setOpaque(false);
        tblSensores.getTableHeader().setBackground(new Color(255, 102, 102));
        tblSensores.getTableHeader().setForeground(new Color(255, 255, 255));
        tblSensores.setRowHeight(25);
    }

    protected void cargarDatosTabla() {
        sensores = sensorDAO.readAllSensors();
        DefaultTableModel model = (DefaultTableModel) tblSensores.getModel();
        model.setRowCount(0);
        for (Sensor sensor : sensores) {
            model.addRow(crearObjetoTabla(sensor));
        }
    }

    private void validarTitulo() {
        if (btnSensoresSelecionado == false) {
            this.txtTitulo.setText("Sensores Desactivados");
        } else if (btnSensoresSelecionado == true) {
            this.txtTitulo.setText("Sensores Activados");
        }
    }

    private Object[] crearObjetoTabla(Sensor sensor) {
        String serie = sensor.getSerie();
        String tipoSensor = validarTipoSensor(sensor);
        boolean estatus = sensor.isStatus();
        String tipoMedicion = validarTipoMedicion(sensor.getData());
        String protocolo = validarProtocolo(sensor.getProtocol());
        int tiempoCaptura = sensor.getTimeInterval();
        return new Object[]{serie, tipoSensor, estatus,
            tipoMedicion, protocolo,
            tiempoCaptura};
    }

    private String validarTipoSensor(Sensor sensor) {
        if (sensor instanceof HumiditySensor) {
            return "Sensor de humedad";
        } else if (sensor instanceof TemperatureSensor) {
            return "Sensor de temperatura";
        }
        return null;
    }

    private String validarTipoMedicion(DataSen data) {
        if (data instanceof HumidityData) {
            return "Humedad "
                    + ((HumidityData) data).getHumidityUnit().toString();
        } else if (data instanceof TemperatureData) {
            return "Temperatura "
                    + ((TemperatureData) data).getTemperatureUnit().toString();

        }
        return null;
    }

    private String validarProtocolo(Protocol protocol) {
        if (protocol instanceof CoapProtocol) {
            return "COAP";
        } else if (protocol instanceof MqttProtocol) {
            return "MQTT";
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        btnIniciarSensores = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JLabel();
        btnComprimir = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSensores = new javax.swing.JTable();
        txtTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        tab1.setBackground(new java.awt.Color(255, 153, 153));

        btnIniciarSensores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciarSensores.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSensores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIniciarSensores.setText("Iniciar Sensores");
        btnIniciarSensores.setVerifyInputWhenFocusTarget(false);
        btnIniciarSensores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSensoresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addComponent(btnIniciarSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIniciarSensores, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sensor.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sensores");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Simulador ");

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("Registar Sensor");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        btnCerrar.setToolTipText("");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });

        btnComprimir.setBackground(new java.awt.Color(255, 51, 51));
        btnComprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comprimir-alt.png"))); // NOI18N
        btnComprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprimirMouseClicked(evt);
            }
        });

        tblSensores.setBackground(new java.awt.Color(255, 255, 255));
        tblSensores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblSensores.setForeground(new java.awt.Color(102, 102, 102));
        tblSensores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serie", "Tipo de sensor", "Estatus", "Tipo de Medición", "Protocolo", "Intervalo de Captura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSensores.setFocusable(false);
        tblSensores.setRowHeight(25);
        tblSensores.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tblSensores.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblSensores.setShowGrid(false);
        tblSensores.getTableHeader().setResizingAllowed(false);
        tblSensores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblSensores);

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprimir)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnComprimir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 790, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnComprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprimirMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnComprimirMouseClicked

    private void btnIniciarSensoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSensoresMouseClicked
        // TODO add your handling code here:
        if (!btnSensoresSelecionado) {
            btnSensoresSelecionado = true;
            this.tab1.setBackground(Color.red);
            inciarSensores();
        } else {
            this.btnSensoresSelecionado = false;
            this.tab1.setBackground(new Color(255, 153, 153));
            pararSensores();
        }
        validarTitulo();
        cargarDatosTabla();
    }//GEN-LAST:event_btnIniciarSensoresMouseClicked

    private void inciarSensores() {
        for (Sensor sensor : sensores) {
            sensor.startSensor();
        }
    }

    private void pararSensores() {
        for (Sensor sensor : sensores) {
            sensor.stopSensor();
        }
    }
    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        registroSensorView.setVisible(true);
    }//GEN-LAST:event_btnRegistrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnComprimir;
    private javax.swing.JLabel btnIniciarSensores;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tab1;
    public static javax.swing.JTable tblSensores;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
