version: '3'

volumes:
  sensor_mysql_data:

services:
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 1234
      
  mysql-sensor:
    image: mysql:latest
    container_name: mysql-sensor
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sensor_db
    ports:
      - "3307:3306"
    volumes:
      - sensor_mysql_data:/var/lib/mysql
